# docker-compose.yaml
# version: 定义希望使用的docker-compose 版本为3.1
version: '3.1'

# services: 声明我们的微服务信息
services:

  datastore:
    image: mongo
    ports:
      - "27017:27017"

  database:
    image: postgres
    ports:
      - "5432:5432"

  user-service:
    build: ./user-service
    ports:
      - "50053:50051"
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"

  # ${micro_service_name}:
  #  build: 指向一个包含Dockerfile的目录，docker-compose会使用此目录下的Dockerfile来编译一个镜像。
  #          也可以使用image来代替，只要image后面指向的是一个已经编译好的镜像即可
  #
  #  ports: 定义宿主机端口以及镜像端口对应关系
  #
  #  environment:
  #    ${env_name}: ${env_value}
  consignment-cli:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"

  consignment-service:
    build: ./consignment-service
    ports:
      - "50051:50051"
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  vessel-service:
    build: ./vessel-service
    ports:
      - "50052:50051"
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"